-- CSH Leasing Rights Control — operational core
-- Canonical migration reconstructed from deployed Supabase schema.

create extension if not exists pgcrypto;

create table if not exists public.shop_master (
  shop_id text primary key,
  project_code text,
  zone text,
  shop_name text,
  source_system text not null default 'LOCAL_MASTER_SHARED',
  source_ref text,
  is_in_scope boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assignment (
  shop_id text primary key references public.shop_master(shop_id) on update cascade on delete restrict,
  cskh_name text,
  cbld_name text,
  source_system text not null default 'LOCAL_MASTER_SHARED',
  source_ref text,
  effective_from date,
  effective_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hdt1 (
  id uuid primary key default gen_random_uuid(),
  shop_id text not null references public.shop_master(shop_id) on update cascade on delete restrict,
  contract_ref text,
  start_date date,
  end_date date not null,
  cktt_end_date date not null,
  status text not null check (status in ('ACTIVE','EXPIRED','LIQUIDATED','CANCELLED')),
  source_system text not null,
  source_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hdt1_end_matches_cktt check (end_date = cktt_end_date)
);

create table if not exists public.hdt2 (
  id uuid primary key default gen_random_uuid(),
  shop_id text not null references public.shop_master(shop_id) on update cascade on delete restrict,
  contract_ref text not null,
  start_date date,
  end_date date,
  status text not null check (status in ('ACTIVE','EXPIRED','LIQUIDATED','CANCELLED')),
  source_system text not null,
  source_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_id, contract_ref, start_date, end_date)
);

create table if not exists public.case_current (
  shop_id text primary key references public.shop_master(shop_id) on update cascade on delete restrict,
  cktt_end_date date,
  days_to_cktt integer,
  onboarded_at timestamptz,
  is_onboarded boolean not null default false,
  hdt2_branch text check (hdt2_branch in ('BEFORE_CKTT','SAME_AS_CKTT','AFTER_CKTT','NO_HDT2','DATA_EXCEPTION')),
  case_status text not null default 'NOT_ONBOARDED' check (case_status in ('NOT_ONBOARDED','IN_PROGRESS','BLOCKED','HANDOVER_PENDING','COMPLETED')),
  next_action text,
  next_action_due date,
  last_progress_at timestamptz,
  stale_days integer,
  warning_level text not null default 'NONE' check (warning_level in ('NONE','INFO','WARNING','CRITICAL')),
  warning_code text,
  handover_check_status text check (handover_check_status in ('NOT_CHECKED','CHECKED')),
  handover_condition text check (handover_condition in ('BELOW_STANDARD','MEETS_STANDARD','ABOVE_STANDARD')),
  repair_status text check (repair_status in ('NOT_REQUIRED','RECORDED','IN_REPAIR','COMPLETED')),
  debt_status text check (debt_status in ('UNKNOWN','PENDING','CLEARED','NOT_APPLICABLE')),
  document_status text check (document_status in ('UNKNOWN','PENDING','COMPLETE','NOT_APPLICABLE')),
  bql_confirmation_status text check (bql_confirmation_status in ('PENDING','CONFIRMED','NOT_APPLICABLE')),
  hdt2_transition_status text check (hdt2_transition_status in ('NOT_APPLICABLE','PENDING','RIGHTS_OBLIGATIONS_DONE','DEPOSIT_DONE','THREE_PARTY_CONFIRMED','COMPLETE')),
  issue_type text,
  issue_text text,
  proposal_text text,
  need_cbld_support boolean not null default false,
  issue_priority text check (issue_priority in ('NORMAL','SOON','URGENT')),
  issue_status text check (issue_status in ('NEW','IN_PROGRESS','RESOLVED')),
  completed_at timestamptz,
  completion_ref text,
  updated_by_cskh text,
  updated_by_cbld text,
  updated_from_session text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.case_event_history (
  id bigint generated by default as identity primary key,
  shop_id text not null references public.shop_master(shop_id) on update cascade on delete restrict,
  event_type text not null,
  field_name text,
  old_value jsonb,
  new_value jsonb,
  actor_role text,
  actor_name text,
  session_id text,
  source text,
  evidence_ref text,
  created_at timestamptz not null default now()
);

create table if not exists public.exception (
  id bigint generated by default as identity primary key,
  shop_id text not null references public.shop_master(shop_id) on update cascade on delete restrict,
  exception_code text not null,
  exception_type text not null,
  severity text not null,
  description text,
  status text not null default 'OPEN',
  requires_cbld boolean not null default false,
  requires_gpt_review boolean not null default false,
  requires_human_authority boolean not null default false,
  opened_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_hdt1_shop_end on public.hdt1(shop_id, end_date desc);
create index if not exists idx_hdt2_shop_dates on public.hdt2(shop_id, start_date, end_date);
create index if not exists idx_case_event_shop_created on public.case_event_history(shop_id, created_at desc);
create index if not exists idx_exception_shop_status on public.exception(shop_id, status);
create index if not exists idx_assignment_cbld_cskh on public.assignment(cbld_name, cskh_name);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_shop_master_updated_at before update on public.shop_master for each row execute function public.set_updated_at();
create trigger trg_assignment_updated_at before update on public.assignment for each row execute function public.set_updated_at();
create trigger trg_hdt1_updated_at before update on public.hdt1 for each row execute function public.set_updated_at();
create trigger trg_hdt2_updated_at before update on public.hdt2 for each row execute function public.set_updated_at();
create trigger trg_case_current_updated_at before update on public.case_current for each row execute function public.set_updated_at();
create trigger trg_exception_updated_at before update on public.exception for each row execute function public.set_updated_at();

alter table public.shop_master enable row level security;
alter table public.assignment enable row level security;
alter table public.hdt1 enable row level security;
alter table public.hdt2 enable row level security;
alter table public.case_current enable row level security;
alter table public.case_event_history enable row level security;
alter table public.exception enable row level security;

-- Intentional: no direct client policies. Frontend access is mediated by the workspace Edge Function.
